#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Oct 20 15:39:00 HKT 2025
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
